---
name: TechDocs
on:
  push: {}
jobs:
  techdocs:
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: read
    name: TechDocs
    # Note: Due to the long name of the the repo + the long branch-names that Dependabot might create,
    # we can exceed the limit of characters allowed in the `google.subject` parameter to google-github-actions/auth.
    # If this happens, a manual workaround is to recreate the PR manually with a shorter branch-name.
    uses: coopnorge/github-workflow-techdocs/.github/workflows/techdocs.yaml@v0
